# Generated by Django 4.0.5 on 2022-06-30 17:32

from django.db import migrations, models
import django.db.models.deletion
import pages.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Osalus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osaluse_suurus', models.PositiveIntegerField(validators=[pages.models.Osalus.validate_osaluse_suurus])),
                ('asutaja', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OsanikModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.TextField()),
                ('kood', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='OsauhinguAndmedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.TextField(validators=[pages.models.OsauhinguAndmedModel.validate_nimi])),
                ('registrikood', models.CharField(max_length=7, unique=True, validators=[pages.models.OsauhinguAndmedModel.validate_registrikood])),
                ('asutamiskp', models.DateField(validators=[pages.models.OsauhinguAndmedModel.validate_asutamiskp])),
                ('kapital', models.PositiveIntegerField(default=5000, validators=[pages.models.OsauhinguAndmedModel.validate_kapital])),
                ('osanikud', models.ManyToManyField(through='pages.Osalus', to='pages.osanikmodel')),
            ],
        ),
        migrations.AddField(
            model_name='osalus',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.osauhinguandmedmodel'),
        ),
        migrations.AddField(
            model_name='osalus',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.osanikmodel'),
        ),
    ]
