# Generated by Django 4.0.5 on 2022-06-24 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OsauhinguAndmed',
            new_name='OsauhinguAndmedModel',
        ),
    ]
