# Generated by Django 4.0.5 on 2022-06-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='osanikmodel',
            name='asutaja',
        ),
        migrations.AddField(
            model_name='osalus',
            name='asutaja',
            field=models.BooleanField(default=False),
        ),
    ]
