# Generated by Django 4.0.5 on 2022-06-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_osauhinguandmedmodel_nimi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osauhinguandmedmodel',
            name='nimi',
            field=models.TextField(max_length=100),
        ),
    ]
